Update RuboCop to make it work in Ruby 3.1
Got the following error when running un GitHub Actions under Ruby 3.1:

    Error: RuboCop found unknown Ruby version 3.1 in `.ruby-version`.
    Supported versions: 2.3, 2.4, 2.5, 2.6, 2.7

Locked rubocop/rubocop-rspec to a specific version to avoid new cops from
showing up each time we run the tests (because this is a gem, we do not have
a lockfile).

Disabled some cops, which we also do in other projects, and also fixed
the following complaints:

    lib/faraday/logfmt_logger/middleware.rb:16:24: C: [Correctable] Style/GlobalStdStream: Use $stdout instead of STDOUT.
              ::Logger.new(STDOUT)
                           ^^^^^^
    lib/twingly/string_utilities.rb:15:16: C: [Correctable] Style/SlicingWithRange: Prefer ary[n..] over ary[n..-1].
            string[1..-1]
                   ^^^^^
    spec/spec_help/test_logger.rb:6:56: C: [Correctable] Style/GlobalStdStream: Use $stdout instead of STDOUT.
      def self.logger_with_log_level_from_env(log_device = STDOUT)
                                                           ^^^^^^

The rest of the complaints were for `RSpec/MultipleMemoizedHelpers`,
and those I just decided to add them to the `rubocop_todo.yml` file
by running (which also updated some comments in that file):

    bundle exec rubocop --auto-gen-config